services:
  nginx:
    image: nginxinc/nginx-unprivileged:stable-alpine
    read_only: true
    user: nginx
    ports:
      - '8080:8080'
    volumes:
      - '/tmp'
      - './docker/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './public/:/var/www/html/public/:ro'

  app:
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
      - './:/var/www/html:delegated'
